# Generated by Django 5.1.4 on 2025-04-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano_de_lancamento', models.IntegerField()),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('romance', 'romance'), ('comedia', 'comedia'), ('terror', 'terror'), ('drama', 'drama'), ('aventura', 'aventura')], max_length=20)),
            ],
        ),
    ]
